### ISSUE TITLE
Error in Visualizing geometry.xml file.

### ISSUE THREAD

**Issue by nilormi94** [fusion-energy/openmc_geometry_plot#23]
When I try to upload my geometry.xml file on https://openmc-plot-4zf6u4tg6a-ew.a.run.app/Geometry_plot, I receive the following error (image attached). 

<img width="554" alt="geometry error" src="https://github.com/fusion-energy/openmc_geometry_plot/assets/86170559/4b6d7cdc-eff0-47cf-968e-a3242bfca8ef">

I have already ran openmc_geometry_plot v0.3.4 from terminal which results out in a local url, on uploading the .xml file in this url , the following error appears:
<img width="831" alt="geometry error_1" src="https://github.com/fusion-energy/openmc_geometry_plot/assets/86170559/cf5e3976-84f8-4fc0-8ae0-37447e3939df">

But visuaslizing source plot works fine i.e. settings.xml.

**Comment by shimwell** [comment]
thanks for letting me know, I've released version 0.3.5 of openmc_geometry_plot which I think fixes the issue. the openmc_plot package now makes use of this and the online app has been rebuilt. Let me know if this works for you and if so then we can close the issue. Thanks for reporting this so clearly, much appreciated

**Comment by nilormi94** [comment]
@shimwell Thank you very much for such a quick fix to this issue. My pleasure. Yes, this issue can be closed.
